steps:
- name: 'docker/compose:1.28.2'
  args: [
    '-p', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/wine-app',
    '-f', './docker-compose.yml',
    'up', '--build', 'web'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'tag',
    'wine-app',
    'europe-west1-docker.pkg.dev/${PROJECT_ID}/wine-app'
  ]
images: ['europe-west1-docker.pkg.dev/${PROJECT_ID}/wine-app']