# steps:
# - name: 'docker/compose:1.28.2'
#   args: [
#     '-p', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/wine-app',
#     '-f', './docker-compose.yml',
#     'build'
#   ]
# - name: 'gcr.io/cloud-builders/docker'
#   args: [
#     'tag',
#     'wine-app',
#     'europe-west1-docker.pkg.dev/${PROJECT_ID}/wine-app'
#   ]
# images: ['europe-west1-docker.pkg.dev/${PROJECT_ID}/wine-app']

# wine-quality-office

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['compose', '-f', 'docker-compose.yml', 'build']
  timeout: 120s

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/wine-quality-office/backend']
  timeout: 120s

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/wine-quality-office/interface']
  timeout: 120s
images: ['gcr.io/wine-quality-office/backend', 'gcr.io/wine-quality-office/interface']



