# steps:
# - name: 'docker/compose:1.28.2'
#   args: [
#     '-p', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/wine-app',
#     '-f', './docker-compose.yml',
#     'build'
#   ]
# - name: 'gcr.io/cloud-builders/docker'
#   args: [
#     'tag',
#     'wine-app',
#     'europe-west1-docker.pkg.dev/${PROJECT_ID}/wine-app'
#   ]
# images: ['europe-west1-docker.pkg.dev/${PROJECT_ID}/wine-app']

# wine-quality-office


# steps:
#   # Build the Docker Compose services
#   - name: 'docker/compose:1.26.2'
#     entrypoint: '/bin/sh'  # Use the shell available in Alpine Linux
#     args:
#       - '-c'
#       - |
#         docker-compose build \
#           --build-arg PROJECT_ID=$PROJECT_ID \
#           --build-arg SHORT_SHA=$SHORT_SHA

#   # Push the container image to Container Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/wine-repo/myimage:$SHORT_SHA']

steps:
  # Build the Docker Compose services
  - name: 'docker/compose:1.26.2'
    entrypoint: '/bin/sh'  # Use the shell available in Alpine Linux
    args:
      - '-c'
      - |
        docker-compose build \
          --build-arg PROJECT_ID=$PROJECT_ID \
          --build-arg SHORT_SHA=$SHORT_SHA

  # Tag the built images with the desired tags
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'workspace_backend:latest', 'europe-west1-docker.pkg.dev/$PROJECT_ID/wine-repo/myimage:$SHORT_SHA-backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'workspace_interface:latest', 'europe-west1-docker.pkg.dev/$PROJECT_ID/wine-repo/myimage:$SHORT_SHA-interface']

  # Push the tagged images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/wine-repo/myimage:$SHORT_SHA-backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/wine-repo/myimage:$SHORT_SHA-interface']







