# steps:
# - name: 'docker/compose:1.28.2'
#   args: [
#     '-p', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/wine-app',
#     '-f', './docker-compose.yml',
#     'build'
#   ]
# - name: 'gcr.io/cloud-builders/docker'
#   args: [
#     'tag',
#     'wine-app',
#     'europe-west1-docker.pkg.dev/${PROJECT_ID}/wine-app'
#   ]
# images: ['europe-west1-docker.pkg.dev/${PROJECT_ID}/wine-app']

# wine-quality-office

steps:

# Build the backend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'backend', './backend']

# Build the interface image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'interface', './interface']

# Push the backend image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend']

# Push the interface image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker' 
  args: ['push', 'gcr.io/$PROJECT_ID/interface']

# Deploy the backend service
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['run', 'deploy', 'backend', '--image', 'gcr.io/$PROJECT_ID/backend', '--port', '8000']

# Deploy the interface service 
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['run', 'deploy', 'interface', '--image', 'gcr.io/$PROJECT_ID/interface', '--port', '8501']

images:
- 'gcr.io/$PROJECT_ID/backend'
- 'gcr.io/$PROJECT_ID/interface'



