version: "3"

services:
  backend:
    container_name: backend
    build: backend/
    ports:
      - "8000:8000"
    networks:
      - deploy_network

  interface:
    container_name: interface
    build: interface/
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - deploy_network

networks:
  deploy_network:
    driver: bridge

